version: '3.5'

services:
  linto-mqtt:
    container_name: linto-mqtt-broker
    image: eclipse-mosquitto
    networks:
      - linto_net

networks:
    internal:
    linto_net:
       external: true
