version: "3.7"

x-labels: &labels
   traefik.enable: "true"
   traefik.http.services.linto-platform-admin.loadbalancer.server.port: 80
   traefik.http.routers.linto-platform-admin.entrypoints: "http"
   traefik.http.routers.linto-platform-admin.rule: "Host(`${LINTO_STACK_DOMAIN}`)"

x-ssl: &ssl
  traefik.http.routers.linto-platform-admin-secure.entrypoints: "https"
  traefik.http.routers.linto-platform-admin-secure.tls: "true" 
  traefik.http.routers.linto-platform-admin-secure.rule: "Host(`${LINTO_STACK_DOMAIN}`)"
  traefik.http.routers.linto-platform-admin.middlewares: "ssl-redirect@file"

x-acme: &acme
  traefik.http.routers.linto-platform-admin-secure.tls.certresolver: "mytlschallenge"

services:
  linto-platform-admin:
    image: lintoai/linto-platform-admin:$LINTO_STACK_IMAGE_TAG
    env_file: .dockerenv
    deploy:
      mode: replicated
      replicas: 1
      labels:
        <<: [ *labels ]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 150s
    
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      # You might bind mount here webserver and vue_app directories for development ;)
    command: # Overrides CMD specified in dockerfile (none here, handled by entrypoint)
      - --reinstall-webserver
      - --rebuild-vue-app
      - --run-cmd=npm run start
    networks:
      - linto-net

networks:
  linto-net:
    external: true
