version: '3.7'

x-mongo-env: &mongo-env
  MONGO_INITDB_DATABASE: $LINTO_STACK_MONGODB_DBNAME

x-mongo-auth: &mongo-auth
  MONGO_INITDB_ROOT_USERNAME: superuser
  MONGO_INITDB_ROOT_PASSWORD: supersecret

services:

  linto-platform-mongo:
    image: mongo:latest
    volumes:
      - ${LINTO_SHARED_MOUNT}/mongoseeds:/docker-entrypoint-initdb.d
      - $HOME/${LINTO_STACK_MONGODB_VOLUME_NAME}/.dbdata:/data/db
      - $HOME/${LINTO_STACK_MONGODB_VOLUME_NAME}/.dbbackup:/data/backup
    labels:
      <<: [ *mongo-env ]
    networks:
      - linto-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  linto-platform-mongo-setup:
    image: mongo:latest
    depends_on:
      - linto-platform-mongo
    volumes:
      - ${LINTO_SHARED_MOUNT}/mongoseeds:/docker-entrypoint-initdb.d
    command: mongo --host linto-platform-mongo ${LINTO_STACK_MONGODB_DBNAME} /docker-entrypoint-initdb.d/admin-users.js
    env_file: .dockerenv
    networks:
      - linto-net
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  linto-net:
    external: true