version: "3.7"

x-labels: &labels
  traefik.enable: "true"
  traefik.tcp.routers.linto-mqtt-in.entrypoints: "mqtt"
  traefik.tcp.routers.linto-mqtt-in.rule: "HostSNI(`*`)" # <== Must specify that
  traefik.tcp.services.linto-mqtt-broker.loadbalancer.server.port: 1883 # <== Send tcp trafic to this port

x-ssl: &ssl
  traefik.tcp.routers.linto-mqtts-in.entrypoints: "mqtts"
  traefik.tcp.routers.linto-mqtts-in.rule: "HostSNI(`${LINTO_STACK_DOMAIN}`)"
  traefik.tcp.routers.linto-mqtts-in.tls: "true"
  traefik.tcp.routers.linto-mqtts-in.tls.passthrough: "false"

x-wss: &wss
  traefik.http.routers.linto-wss-in.entrypoints: "https"
  traefik.http.routers.linto-wss-in.rule: "Host(`${LINTO_STACK_DOMAIN}`) && (PathPrefix(`${LINTO_STACK_MQTT_OVER_WS_ENDPOINT}`))"
  traefik.http.routers.linto-wss-in.tls: "true"
  traefik.http.middlewares.linto-wss-in.stripprefix.prefixes: ${LINTO_STACK_MQTT_OVER_WS_ENDPOINT}
  traefik.http.services.linto-mqtt-broker.loadbalancer.server.port: 9001 # < == Port setup in config/mosquitto/mosquitto.conf

x-ws: &ws
  traefik.http.routers.linto-ws-in.entrypoints: "http"
  traefik.http.routers.linto-ws-in.rule: "Host(`${LINTO_STACK_DOMAIN}`) && (PathPrefix(`${LINTO_STACK_MQTT_OVER_WS_ENDPOINT}`))"
  traefik.http.middlewares.linto-ws-in.stripprefix.prefixes: ${LINTO_STACK_MQTT_OVER_WS_ENDPOINT}
  traefik.http.services.linto-mqtt-broker.loadbalancer.server.port: 9001 # < == Port setup in config/mosquitto/mosquitto.conf

x-acme: &acme
  traefik.tcp.routers.linto-mqtts-in.tls.certresolver: "mytlschallenge"

x-acme-wss: &acme-wss
  traefik.http.routers.linto-wss-in.tls.certresolver: "mytlschallenge"
  traefik.tcp.routers.linto-mqtts-in.tls.certresolver: "mytlschallenge"

services:
  linto-mqtt-broker:
    image: iegomez/mosquitto-go-auth:1.5.0
    env_file: .dockerenv
    deploy:
      mode: replicated
      replicas: 1
      labels:
        <<: [ *labels ]
    volumes:
      - ${LINTO_SHARED_MOUNT}/config/mosquitto/:/etc/mosquitto
      - ${LINTO_SHARED_MOUNT}/data/mosquitto/:/mosquitto/data
    networks:
      - linto-net

networks:
  linto-net:
    external: true
